version : '3.8'
services:
 
  springappserver:
    build:
      dockerfile: Dockerfile
    ports:
      - "8192:8192"
    restart: unless-stopped  
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: docker_mongo 
    restart: unless-stopped   
    volumes:
      - .:/db    
    command: mongod --port 27017
    ports:
      - 27017:27017
    command: [ "--bind_ip", "0.0.0.0" ]
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express   
    ports:
      - 8200:8081
    restart: unless-stopped 